// <auto-generated />
using FociWebApp_2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FociWebApp_2.Migrations
{
    [DbContext(typeof(FociDbContext))]
    partial class FociDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("FociWebApp_2.Models.Meccs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fordulo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HazaiGolFelido")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HazaiGolok")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HazaiNev")
                        .HasColumnType("TEXT");

                    b.Property<int>("VendegGolFelido")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VendegGolok")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VendegNev")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Meccsek");
                });
#pragma warning restore 612, 618
        }
    }
}
